baseURL: "https://bryzenmorales.github.io/" 
title: Bryzen Enzo Morales
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        # - name: Books
        #   url: books/
        #   weight: 5 
        - name: Home
          url: /
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        #- name: Publications
        #  url: publications/
        #  weight: 3
        #- name: Briefs
        #  url: briefs/
        #  weight: 4
        #- name: Other
        #  url: somestuff/
        #  weight: 4
          

params:
    description: "I am currently a Public Affairs and Economics undergraduate student at the University of California, Los Angeles (UCLA). I am an aspiring applied, quantitative social scientist, interested in problems related to poverty and social inequality."
    author: Bryzen Enzo Morales
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Bryzen Enzo Morales
          subtitle: "I am currently a Public Affairs and Economics undergraduate student at the University of California, Los Angeles (UCLA). 
          I am an aspiring applied, quantitative social scientist, interested in problems related to poverty and social inequality." 
          #imageUrl: 
          #imageWidth: 160
          #imageHeight: 160
          #imageTitle: Bryzen Enzo Morales
          buttons:
             - name: Projects
               url: projects/
            # - name: Publications
            #   url: publications/
            # - name: Briefs
            #   url: briefs/
            # - name: Others
            #   url: somestuff/
            # - name: Archive
            #   url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:bryzen062904@g.ucla.edu
          # url: location/
        # - name: Office Hours
        #   url: officehours/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=K5aOUegAAAAJ&hl
        - name: GitHub
          url: https://github.com/bryzennnnn
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@alexandermccallsmithoffici9000


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    #label:
      #text: "Daniel AC Barbosa"
     # icon: favicon.ico
      #iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
